import Head from 'next/head'
import Link from 'next/link';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import Cart from './cart';

const Layout = ({ children}) => {
  const [display, setDisplay] = useState(false)
  const cart = useSelector(state => state.cart)
  return (
    <>
      <Head>
        <title>Default Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className='px-8 bg-gray-800 h-12 fixed w-full'>
        <nav className='flex justify-between h-full items-center'>
          <h1>Default store</h1>
          <div className='flex gap-4 items-center'>
            <Link href={'/'}>Home</Link>
            <button 
              onClick={() => setDisplay(state => !state)}
              className={`p-1 rounded-md hover:bg-cyan-800 transition-colors ${display && "bg-zinc-600"}`}
            >Cart {`(${cart.length})`}</button>
          </div>
        </nav>
      </header>
      <main className='pt-24'>{children}</main>
      <Cart display={display}/>
    </>
  );
};

export default Layout;
